### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by yutiansut** [ajdavis/mongo-mockup-db#11]
localhost environment

- i7 8700k 32G DDR4
- mongodb 3.6 
- pymongo3.6

I use ```pip install git+https://github.com/ajdavis/mongo-mockup-db``` to install this project and stop the original mongodb on windows with ``` net stop mongodb```
and use ``` python -m mockupdb``` to connect from the shell

while then when I connect to mongo using pymongo, it successed. however when i want to insert something, it return out the error below
```
ConfigurationError: Server at 127.0.0.1:27017 reports wire version 0, but this version of PyMongo requires at least 2 (MongoDB 2.6).
```

**Comment by ajdavis** [comment]
Thanks for reporting!
