### ISSUE TITLE
Remove vendored bson

### ISSUE THREAD

**Issue by kevinAlbs** [ajdavis/mongo-mockup-db#18]
The bson library is vendored from PyMongo 3.0.3 according to [this comment](https://github.com/ajdavis/mongo-mockup-db/blob/master/mockupdb/__init__.py#L68).

This seems to have an issue encoding binary, crashing on [this line when logging](https://github.com/ajdavis/mongo-mockup-db/blob/master/mockupdb/__init__.py#L1924).

A simple repro, comparing dumps from pymongo 3.7.1  and from the vendored dumps from mockupdb:
```
from bson import json_util
import mockupdb._bson.json_util as mockup_json_util

doc = {
    "bin": Binary(b'\x17\x00\x01\x06\xb0\x7b\x00\x01\x76\x00\x00\x00\x00\x40\x00')
}

print("dumping with pymongo: {0}".format(json_util.dumps(doc)))
print("dumping with mockupdb: {0}".format(mockup_json_util.dumps(doc)))
```

The first print succeeds, but the second print crashes with a traceback:
```
dumping with pymongo: {"bin": {"$binary": "FwABBrB7AAF2AAAAAEAA", "$type": "00"}}
Traceback (most recent call last):
  File "/Users/kevinalbertson/code/mockupcryptd/test.py", line 1, in <module>
    import mockupcryptd
  File "/Users/kevinalbertson/code/mockupcryptd/mockupcryptd/__init__.py", line 20, in <module>
    print("dumping with mockupdb: {0}".format(mockup_json_util.dumps(doc)))
  File "/Users/kevinalbertson/Documents/cenv/lib/python2.7/site-packages/mockupdb/_bson/json_util.py", line 411, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 4: invalid start byte
```

Encountered on macOS 10.12, Python 2.7.10. I assume this was fixed sometime after pymongo 3.0.3, so I think updating the vendored bson library would fix this.

**Comment by ajdavis** [comment]
Updating the vendored BSON is a good idea, but this is not related. It's interesting, actually: json_util does "isinstance(obj, Binary)" to decide whether to special-case the JSON encoding of a Binary object. There are two Binary classes in the Python runtime in your example: one in PyMongo's bson module, the other in MockupDB's vendored bson module. "isinstance" considers them different and returns False.

This works:
```
mockup_json_util.dumps({
    "bin": mockup_bson.Binary(
        b'\x17\x00\x01\x06\xb0\x7b\x00\x01\x76\x00\x00\x00\x00\x40\x00')
})
```
This is a very sharp edge of the library, lemme think more about how to prevent it in MockupDB.

**Comment by ajdavis** [comment]
Changed title from "update vendored bson" to "remove vendored bson": it's less error-prone if we depend on PyMongo's bson.
