### ISSUE TITLE
No matching distribution found for mongo-mockup-db

### ISSUE THREAD

**Issue by jokinr** [ajdavis/mongo-mockup-db#22]
Windows 10

>pip -V
pip 18.1 from c:\python36\lib\site-packages\pip (python 3.6)

>python --version
Python 3.6.7

>python -m pip install mongo-mockup-db
Collecting mongo-mockup-db
  Could not find a version that satisfies the requirement mongo-mockup-db (from versions: )
No matching distribution found for mongo-mockup-db

**Comment by ajdavis** [comment]
It should be "python -m pip install mockupdb", sorry for the mistake. I've fixed the installation instructions now.
