### ISSUE TITLE
mockupdb with asyncio

### ISSUE THREAD

**Issue by yunstanford** [ajdavis/mongo-mockup-db#24]
Didn't look into implementation, does it work with async ?

will take a look later in details.

**Comment by ajdavis** [comment]
I'm going to close this. Please reopen if you can describe a specific bug or feature that you want. Please describe how you expect MockupDB to behave, and how it actually behaves. Here's a good guide for filing bug reports: https://stackoverflow.com/help/mcve

**Comment by yunstanford** [comment]
sorry about that. I'll try play with it and get back to you. Thanks.
