### ISSUE TITLE
Using mockup-db to unit-test motor application

### ISSUE THREAD

**Issue by brean** [ajdavis/mongo-mockup-db#25]
Hi,

I have a motor application that I'd like to unit-test using MockupDB, but I don't know how.

for example I like to test if this small thing creates a valid user:
```
async def create(db, mail='some.user@example.com'):
    if not check_mail(mail):
        logging.error('invalid mail')
        return None
    [...]
    return await db.users.insert_one({'mail': mail})
```

According to the documentation I should wrap the insert_one using mockupdb.go, and call it synchronous. Do I have to refactor my code so it wraps all queries in `go` and can I use that in production?

**Comment by brean** [comment]
In this simple example I could assume that MongoDB is just doing its thing (storing the user correctly) and just test if my check_mail function does what it should do, but if I have some more complex algorithms with multiple collections involved. I might need to refactor this code to modify data outside of mongo and use it just as untested persistence layer ontop of my data.

**Comment by ajdavis** [comment]
Happy to help. But I don't yet understand why you need MockupDB for this instead of testing your code with MongoDB. I think it would be simpler to avoid MockupDB. Definitely do not use `go` in production! It spawns a new thread for every operation, very expensive and risky. Anyway here's a sketch of testing Motor with MockupDB. I'm assuming you use asyncio:
```
import asyncio
import logging
import unittest

from mockupdb import MockupDB, going, OpMsg

from motor.motor_asyncio import AsyncIOMotorClient


def check_mail(_):
    return True


async def create(db, mail='some.user@example.com'):
    if not check_mail(mail):
        logging.error('invalid mail')
        return None

    return await db.users.insert_one({'mail': mail})


class MyTest(unittest.TestCase):
    def test(self):
        # In a real test, omit "verbose".
        server = MockupDB(verbose=True, auto_ismaster=True)
        server.run()
        self.addCleanup(server.stop)  # Important!
        client = AsyncIOMotorClient(server.uri)
        loop = asyncio.get_event_loop()
        with going(loop.run_until_complete, create(client.test)) as future:
            # Use pattern-matching or asserts to assert what you want about
            # the request.
            request = server.receives(OpMsg('insert', 'users'))
            self.assertEqual(request.doc['documents'][0]['mail'],
                             'some.user@example.com')

            # You could do request.hangup() or request.command_err() to test
            # error handling.
            request.ok()

        # Get the return value of create(), which was passed back through
        # run_until_complete() and going().
        result = future()
        # Just a pymongo.results.InsertOneResult.
        print(result)


if __name__ == '__main__':
    unittest.main()
```

**Comment by brean** [comment]
Yeah, that's what I was looking for! Thank you very much!

I run my tests on gitlab-ci, in a docker container. I did not thought to much about setting up mongodb in my testing process, that seemed also kind of wrong to me, but I will try to create a docker container that provides me with mongo-server before I test your code some more. That's maybe also the clearer implementation because I test on the actual system that will be used in production later.

(I assumed setting up the container would be hard but [this](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services) looks quite simple... I'll give it a try )

**Comment by ajdavis** [comment]
Great! I'll close this but feel free to reopen if you have more questions.

**Comment by kob22** [comment]
Hi, I wanted to mockup-db with MotorClient, I tried your solution, but it doesn't work for me. I've got timeout.

`@pytest.mark.asyncio
async def test_create_document_in_DB():
    """
    Test creates document in DB from Document schema
    :return:
    """
    document_example = internal.Document(
        internal_collection_id="id_collection_some_string",
        collection_name="important documents",
        high_priority=True,
        status="in progress",
        progress=50,
        interventions=12,
        interventions_type=["Extract"],
    )
    server = MockupDB(verbose=True, auto_ismaster=True)
    server.run()

    client = AsyncIOMotorClient(server.uri)
    loop = asyncio.get_event_loop()
    with going(loop.run_until_complete, document.create_document(client, document_example)) as future:
        # Use pattern-matching or asserts to assert what you want about
        # the request.
        request = server.receives(OpMsg('insert', 'documents'))

        # You could do request.hangup() or request.command_err() to test
        # error handling.
        request.ok()

    # Get the return value of create(), which was passed back through
    # run_until_complete() and going().
    result = future()
    # Just a pymongo.results.InsertOneResult.
    print(result)`

**Comment by ShaneHarvey** [comment]
Hi @kob22, please open a new issue if you're still facing this problem. It would be helpful to include the python version, `python -m pip list` output, OS, and any other relevant environment info.
