### ISSUE TITLE
Insert instruction exception

### ISSUE THREAD

**Issue by Dyoung-1** [ajdavis/mongo-mockup-db#26]
hi     Why is it that when I send 'db.person.insert({"name": "kelvin", "age": 35})' on the client side, the server parse throws an 'First OP_MSG payload type must be 0 not 1' exception

**Comment by ajdavis** [comment]
Can I see a complete Python script that reproduces this error, please?

**Comment by Dyoung-1** [comment]
> Can I see a complete Python script that reproduces this error, please?

Of course,    
step 1  : I started MockupDB with IDEA  
![image](https://user-images.githubusercontent.com/55119665/65739247-2606fb80-e117-11e9-8699-6a48c8cff555.png)
step 2: Connect by mongo.exe
![image](https://user-images.githubusercontent.com/55119665/65739287-4a62d800-e117-11e9-872d-0a9b60a9f30a.png)
step 3: CMD enters insert instruction 
![image](https://user-images.githubusercontent.com/55119665/65739333-6f574b00-e117-11e9-8e19-67faa74fd163.png)
step 4 :An error
![image](https://user-images.githubusercontent.com/55119665/65739503-12a86000-e118-11e9-9a39-34de3a0cdaa9.png)

**Comment by ajdavis** [comment]
Oh, this is actually my fault. I implemented [message checksum support in the mongo shell](https://jira.mongodb.org/browse/SERVER-28679) in version 4.2.0, so now the shell sends messages with the "checksumPresent" flag set, that's flag bit 1.

MockupDB wasn't updated to expect messages with checksums, so it throws an error.

**Comment by Dyoung-1** [comment]
> Oh, this is actually my fault. I implemented [message checksum support in the mongo shell](https://jira.mongodb.org/browse/SERVER-28679) in version 4.2.0, so now the shell sends messages with the "checksumPresent" flag set, that's flag bit 1.
> 
> MockupDB wasn't updated to expect messages with checksums, so it throws an error.

Oh, I see. Now it works. Thanks for the answer.

**Comment by ajdavis** [comment]
Reopening this issue - we do need to fix it.
