### ISSUE TITLE
Drop support for Python 2.6 and 3.3

### ISSUE THREAD

**Issue by ShaneHarvey** [ajdavis/mongo-mockup-db#29]
Since https://github.com/ajdavis/mongo-mockup-db/commit/c25a25f2728ef3c0dd13cc798ec4bdc1eeb574a4#diff-354f30a63fb0907d4ad57269548329e3 we have not been testing Python 2.6 support. We should officially drop support for it.

Let's remove support for 2.6 in setup.py and remove the 2.6 reference in: https://mockupdb.readthedocs.io/contributing.html#pull-request-guidelines

**Comment by ajdavis** [comment]
After this, remind me to publish a new release.
