### ISSUE TITLE
Use mockupdb with pymodm and mock default value in field

### ISSUE THREAD

**Issue by arut-grigoryan** [ajdavis/mongo-mockup-db#34]
I use flask-pymodm. How I to mock `UUID, ObjectId, datetime`?
Example:
```
class MyClass(MongoModel):
    uuid = fields.UUIDField(default=uuid.uuid4)

    @staticmethod
    def create():
        my_object= MyClass().save()
        response = {
            "uuid": my_object.uuid,
        }
        return response
```
Test:
```
@pytest.fixture
def mongoServerAndFlaskClient():
    app = Flask(__name__)
    app.config.from_object('app_config.TestingConfig')
    server = MockupDB(auto_ismaster=True)
    server.run()
    app.config['MONGODB_HOST'] = server.host
    app.config['MONGODB_PORT'] = str(server.port)
    with app.test_client() as client:
        with app.app_context():
            initializeDb(app)
            set_before_request(app)
            import rest.dms.routes
            yield server, client
    server.stop()

def test_create(mongoServerAndFlaskClient):
    mongo_server, flask_client = mongoServerAndFlaskClient
    future = go(
        flask_client.post,
        "/my_class/create",
    )
    request = mongo_server.receive()
    http_response = future()
    assert json.loads(http_response.get_data(as_text=True)) == my_test_dict
```
I use pytest-mocker, but it didn't work
`mocker.patch("uuid.uuid4", return_value=uuid.UUID("5d3d31f7b5614dfe82e36f35140d3e48"))`

**Comment by ShaneHarvey** [comment]
mongo-mockup-db is designed to test the low-level internals of pymongo itself. mongo-mockup-db isn't really the best way to test application code using pymongo/pymodm. Instead, I suggest you test against a real mongodb instance.

To address your original question: Why do you want to mock UUID, ObjectId, and datetime? Can you assert the shape of the returned data instead of doing an exact match? For example:

```
    res = json.loads(http_response.get_data(as_text=True))
    assert set(res.keys()) == {'_id', 'uuid'}
    assert isinstance(res['_id'], ObjectId)
    assert isinstance(res['uuid'], UUID)
```

**Comment by arut-grigoryan** [comment]
I can check the form. And then delete them, and check the static data.

> mongo-mockup-db is designed to test the low-level internals of pymongo itself. mongo-mockup-db isn't really the best way to test application code using pymongo/pymodm. Instead, I suggest you test against a real mongodb instance.

Or you can suggest some option for testing? Didn't find anything else to test pymodm.

**Comment by ShaneHarvey** [comment]
You can test against a real MongoDB server. That's how we test pymodm itself: https://github.com/mongodb/pymodm/blob/0.4.3/.travis.yml

> I use pytest-mocker, but it didn't work
> `mocker.patch("uuid.uuid4", return_value=uuid.UUID("5d3d31f7b5614dfe82e36f35140d3e48"))`

I think this patch didn't work because the `MyClass.uuid` field already has a reference to the real `uuid4` method. Try changing MyClass like this:
```
class MyClass(MongoModel):
-    uuid = fields.UUIDField(default=uuid.uuid4)
+    uuid = fields.UUIDField(default=lambda: uuid.uuid4())
```

**Comment by arut-grigoryan** [comment]
As a result, we decided to create a docker container with mongodb for testing. After the tests, we just delete the container. I think I can close the issue. Thank you!
