### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by onovy** [ajdavis/mongo-mockup-db#5]
Please tag 1.1.1 and 1.1.2 release in git.

Thanks.

**Comment by onovy** [comment]
and
1.1.3
1.2.0
1.2.1

thanks again.

**Comment by ajdavis** [comment]
Done. I'm curious, what are you using MockupDB for? Why are the release tags important?

**Comment by onovy** [comment]
I'm maintainer of Debian package:
https://packages.debian.org/sid/source/python-mockupdb

Tags are important for automatic checking if there is new release. But I'm using pypi for it now (https://sources.debian.org/src/python-mockupdb/1.2.1-1/debian/watch/)

**Comment by ajdavis** [comment]
Got it. Thanks for packaging this! I didn't know it was in Debian.
