### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by wilsonge** [ajdavis/mongo-mockup-db#9]
Is there a recommended way for how to deal with Mongo Authentication in an application using this box? Whilst technically you can end up with the mongo auth failing and there should be tests for that, I'm more thinking about how to ensure a positive response to SCRAM-SHA-1 auth (or whatever else is being used) - it seems like there should be some sort of autoresponder for this like there is for the  ismaster check - but it's much harder because it actually depends on the request document (for the nonce)

**Comment by ajdavis** [comment]
Seems tricky. I don't personally have a need to implement the server side of authentication. If you can implement it as an example or a builtin feature of the MockupDB server let me know.

**Comment by wilsonge** [comment]
Python deprecated DB auth in the meantime anyhow. Closing as it's kinda a non-issue when you have authentication credentials in the url.

**Comment by ajdavis** [comment]
Right, agreed. Thanks for responding! I am curious what you're using MockupDB for?

**Comment by wilsonge** [comment]
I was using it to do some failover testing for a flask/mongo application I've been experimenting with https://emptysqua.re/blog/test-mongodb-failures-mockupdb/ (I mean that example no longer works but similar principle)

**Comment by ajdavis** [comment]
Great to see it used as intended! I've fixed the example for the modern "find" command protocol. Let me know if you publish any code or write about your experience.
